lib/angstrom.ml, lib_test/test_angstrom.ml
This pull requests fixes bugs in including `sep_by1`, `take_while`, and `take_while1`. The `sep_by1` affected all sorts of inputs, while the `take_while` bug would only surface when reading input across chunk boundaries.
=> various bugfixes

lib/angstrom.ml, lib/angstrom.mli, lib_test/test_angstrom.ml
This pull request adds the `count`, `skip_while` and `skip_while1` to the Angstrom API. Documentation for each can be found in the mli file.
=> additional iteration combinators

benchmarks/pure_benchmark.ml
The pure benchmark code was defining its own skip_many combinator, which is already defined the main module. A comment in that benchmark code also contained a typo, which was corrected.
=> benchmark: simplify implementation, fix comments

rfcs/rFC2616.ml
This pull request includes a bugfix in the response RFC2616 response parser, as well as a performance improvement to various components of the RFC2616 parser. Microbenchmarks suggest a 30% performance improvement for request parsing.
Here are the results of the benchmark before the patches:
```
$ ./pure_benchmark.native -q 60 +time
Estimated testing time 2m (2 benchmarks x 1m). Change using -quota SECS.
┌──────┬──────────┬──────────┬───────────────┬─────────┬──────────┬──────────┬────────────┐
│ Name │ Time R^2 │ Time/Run │          95ci │ mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├──────┼──────────┼──────────┼───────────────┼─────────┼──────────┼──────────┼────────────┤
│ json │     1.00 │  21.07ms │ -0.55% +0.55% │ 18.78Mw │ 242.08kw │ 242.08kw │     44.79% │
│ http │     1.00 │ …
```
=> RFC2616 bug fix and performance improvement

lwt/angstrom_lwt.ml
`Lwt.yield ()` is a more preferable choice, as that would ensure that parsing thread would allow other threads to run. However, that function is exported by a module in the unix subpackage, and is therefore not portable to other platforms (JS, mirage, etc.)
=> lwt-unit: Use Lwt.return_unit as default pushback

lib/angstrom.ml, lib/angstrom.mli, rfcs/rFC2616.ml, rfcs/rFC7159.ml
This pull request adds implementations for the `lift` family of functions of up to four arguments. These functions are more efficient than using the applicative interface directly, and should therefore be preferred.
=> implement lift functions up to 4

benchmarks/pure_benchmark.ml, lib/angstrom.ml, lib/angstrom.mli, lib_test/test_angstrom.ml
For #22
A few notes:
- If I understand correctly the `_unsafe` modules should be ok to use
here since the number of bytes is restricted in the wrappers around
the EndianString.* functions.
- The Make_endian functor may add some overhead on compilers without
flambda enabled/available.  I used a functor here anyway to avoid lots
of copying and pasting.  The interface is duplicated because it makes
the generated documentation easier to read but that duplication could
be eliminated with a module type defintion.
- If the source is a cstruct then EndianBigString.* working directly
with the cstruct-wrapped bigarrays could avoid lots of string
allocations from the `take` calls.
No tests or benchmarks yet - I'd like to agree on naming and basic implementation first.
=> Add basic little/big/native endian parsing

lib/angstrom.ml
The previous version was optimizing for a case where the input would be read in chunks, which would then be concatenated and then returned to the user. No such case exists for this library, so the more straightforward implementation turns out to be the faster one.
Before:
```
┌──────────┬──────────┬─────────────┬───────────────┬─────────────┬──────────┬──────────┬────────────┐
│ Name     │ Time R^2 │    Time/Run │          95ci │     mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├──────────┼──────────┼─────────────┼───────────────┼─────────────┼──────────┼──────────┼────────────┤
│ json     │     1.00 │ 16_399.20us │ -0.82% +0.84% │ 11_694.02kw │ 213.75kw │ 213.75kw │     65.36% │
│ http     │     1.00 │ 25_089.50us │ -0.54% +0.56% │ 13_384.76kw │  56.45kw │  56.45kw │    100.00% │
│ int8 …
```
=> take_while1: rely on take_while entirely for its implementation

rfcs/rFC7159.ml
This pull request improves the performance and memory-efficiency of the JSON parser provided in the `rfcs` directory of the repository. The main performance gain is due to a new approach to parsing strings, which does not allocate intermediate strings, and does not rely on backtracking.
Before:
```
┌──────┬──────────┬──────────┬───────────────┬─────────┬──────────┬──────────┬────────────┐
│ Name │ Time R^2 │ Time/Run │          95ci │ mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├──────┼──────────┼──────────┼───────────────┼─────────┼──────────┼──────────┼────────────┤
│ json │     1.00 │  15.98ms │ -1.25% +1.05% │  9.54Mw │ 208.07kw │ 208.07kw │    100.00% │
└──────┴──────────┴──────────┴───────────────┴─────────┴──────────┴──────────┴────────────┘
```
After:
``` …
```
=> improve json parsing performance and memory-efficiency

lib/angstrom.ml, lib/angstrom.mli
The char parsers as implemented previously required the use of binds, leading to unnecessary allocations of intermediate parser and therefore closures. With this patch the new char parsers (with the exception of `peek_char`) are built from a single `_char` primitive parser. This parser requires that there is at least one more character in the input, and fails otherwise. Its function argument is applied to the character and and transforms it to an optional value. If the function returns `Some v` then parser succeeds with value `v`, and fails otherwise.
Before:
```
┌──────────┬──────────┬─────────────┬───────────────┬────────────┬──────────┬──────────┬────────────┐
│ Name     │ Time R^2 │    Time/Run │          95ci │    mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │ …
```
=> char: reduce allocations from use of char parser

README.md, lib/angstrom.ml, lib/angstrom.mli
Note that it may be useful to use `peek_string` in conjunction with `parse_only` if there is a need to extract some structure from the lookahead range.
=> peek_string: add support for unbounded lookahead

async/angstrom_async.ml, lib/angstrom.ml, lib/angstrom.mli
This pull request clarifies the use of the use of the terms "commit" and "consume" in the API. A parser may consume input but still retain the ability to backtrack. A parser however cannot backtrack beyond a commit point.
In addition, this pull request reports the parser's position upon completing a successful parse, something that is important to report if it has not consumed all of its input.
=> committed: clarify consumed vs committed

lwt/angstrom_lwt_unix.ml
`Lwt.Infix` was introduced in 2.4.7. Just open `Lwt` to avoid the lower bound on the lwt version.
Related to ocaml/opam-repository#7169
=> lwt-infix: open Lwt instead of Lwt.Infix

benchmarks/pure_benchmark.ml, lib/angstrom.ml, lib/angstrom.mli, lib_test/test_angstrom.ml
This pull request affects the endian parsers in the following way:
* `int8` and `uint8` have been dropped from the interface, since they are only one byte long and therefore byte order cannot affect how they're parsed; and
* the `Ne` native-endian module has been dropped, since using it may result in inconsistent parser behavior.
=> endian: drop certain endian parsers

lib/angstrom.ml, lib/angstrom.mli
This pull request makes two changes to the public API:
* It removes the `take_rest` parser, which would accept all remaining input, returning it in chunks to the user. This parser was a bad idea due to its memory characteristics: it required all remaining input to be in memory, all at once, which would be copied incrementally into chunks, and then finally returned. 
* It remove `want_input` from the "private API" section and introduces the related `at_end_of_input` parser. The two are related in that `at_end_of_input = want_input >>| not`.
=> add at_end_of_input parser

lib/angstrom.mli
This pull request adds the `advance` parser to the public API. This parser is useful for when you want to skip a region of input without having to copy the region to a newly-allocated buffer, as the previous public API required.
=> advance: add advance to public API

benchmarks/pure_benchmark.ml, lib/angstrom.ml, lib/angstrom.mli, lib_test/test_angstrom.ml
This pull request goes back to the original signature setup for the big endian and little endian parser modules, while also capitalizing the 'e' in the module names; `Le` is now `LE` and `Be` is now `BE`.
Playing feature ping-pong with #50. :(
=> endian: inline signatures, capitalize E

lib/angstrom.ml, lib/angstrom.mli
As discussed in #61, this PR adds a variance annotation to `'a Angstrom.t`, such that is is covariant in `'a`. This makes `Angstrom.t` play well with polymorphic variants.
Example:
```ocaml
let x : [`Foo] Angstrom.t  = Angstrom.return `Foo;;
let y = (x :> [`Foo | `Bar] Angstrom.t);;
```
Previously the example above would be rejected with the error ```Type [ `Foo ] Angstrom.t is not a subtype of [ `Bar | `Foo ] Angstrom.t```.
I haven't added any tests -- let me know if you'd like that.
=> Make Angstrom.t covariant

lib/angstrom.mli
This PR edits the API docs.
I was unsure of one of the things: using `[input]` in one spot. Just revert that if needed.
=> Copy-edits to mli

async/angstrom_async.ml, lib/angstrom.ml, lib/angstrom.mli
The Fail state for the Unbuffered interface previously did not return
indicate where in the input the parse failed. While this is not the most
useful information for parsers that make use of extensive backtracking,
it can help in some cases.
As part of the change, move the position information for both the
Buffered and Unbuffered state types to be the first value contained in
the variant.
Addresses #69
=> positions: consistently return success and failure position

lib/angstrom.mli
=> fix-ocamldoc: fix various broken references in ocamldoc comments

angstrom.opam, lib_test/test_angstrom.ml
A epsilon parameter was added to Alcotest.float.  Using 0.0 seems
appropriate here as we're testing for precise equality.
The opam constraint is set to 0.8.1 as 0.8.0 didn't properly support an epsilon of 0.0.
=> Update to use and support the latest Alcotest

README.md
The previous implementation was for `chainr1`.
Closes #90
=> fix-chainl1: fix implementation of chainl1

lib/angstrom.ml, lib/bigstring.ml, lib/bigstring.mli, lib/jbuild
In order to improve code organization, move Bigstring operations into an internal module. This will not be exposed in the public API.
=> move-bigstring: collect Bigstring operations into internal module

angstrom.opam, lib/angstrom.ml, lib/angstrom.mli, lib/buffering.ml, lib/buffering.mli, lib/jbuild
This was just used for the buffered interface. Specifically for access to the `memcpy` C stubs. However, this interface is not performance-sensitive, so just drop the dependency, and allocate a bit
less along the way.
=> remove-cstruct: remove the dependency on cstruct

lib/bigstring.ml, lib/bigstring_stubs.c, lib/jbuild, lib/runtime.js
In the latest move away from cstructs, the library lost access to a `memcpy` based blit operation, which slowed down the HTTP  by a bit. Here's the regression at the parent of this PR:
```
┌──────────┬─────────────┬────────────┬──────────┬──────────┬────────────┐
│ Name     │    Time/Run │    mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├──────────┼─────────────┼────────────┼──────────┼──────────┼────────────┤
│ http     │ 57_108.98us │ 7_626.20kw │  52.65kw │  52.65kw │    100.00% │
└──────────┴─────────────┴────────────┴──────────┴──────────┴────────────┘
```
and here are the benchmarks at the tip of this PR:
```
┌──────────┬─────────────┬────────────┬──────────┬──────────┬────────────┐
│ Name     │    Time/Run │    mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │ …
```
=> Fix performance regression

lib/bigstring_stubs.c
Without this, blits will apply incorrectly for larger buffers.
I ran into this doing some stress testing with several gigabyte buffers.
=> Use Long_val for C stubs

lib/angstrom.ml, lib/angstrom.mli, lib/bigstring.ml, lib/bigstring.mli, lib_test/test_angstrom.ml
Useful now that the internal buffer is always a bigstring.
=> Add take_bigstring function

angstrom-async.opam
Pointed out by @andreas in ocaml/opam-repository#10286.
=> fix-angstrom-async-contraints: require angstrom >= 0.7.0

lib/angstrom.ml, lib_test/test_angstrom.ml
In my mind, `peek_char` could never fail. In my implementation of `ocaml-git`, I need at a specific point to load directly all of the input in a `Buffer.t`:
```ocaml
let decoder len =
let buf = Buffer.create len in
let open Angstrom in
fix @@ fun m ->
available >>= function
| 0 ->
peek_char
>>= (function
| Some _ -> commit *> m
| None ->
let cs = Cstruct.of_string (Buffer.contents buf) in
Buffer.clear buf;
return cs <* commit)
| n -> take n >>= fun chunk ->
Buffer.add_string buf chunk;
commit *> m
```
This is a __non-optimized__ way to load all of the input in a `Buffer.t` and return at the end a `Cstruct.t`.
The problem concern the combinator `peek_char`. Indeed, when we consume all of the current `input`, we call `peek_char` to call indirectly `prompt` and ask to the user to refill the …
=> Fixed the peek_char combinator

lib/bigstring.ml
Prior to this commit, `caml_ba_get_N` was at the top of the perf report for the json benchmark. Using intrinsics, those have disappeared from the report and performance has improved.
Before:
```
┌─────────────┬─────────────┬────────────┬─────────────┬─────────────┬────────────┐
│ Name        │    Time/Run │    mWd/Run │    mjWd/Run │    Prom/Run │ Percentage │
├─────────────┼─────────────┼────────────┼─────────────┼─────────────┼────────────┤
│ twitter1    │     26.07us │     7.56kw │      10.07w │      10.07w │      0.14% │
│ twitter10   │    184.28us │    46.83kw │     270.51w │     270.51w │      0.99% │
│ twitter20   │    349.57us │    92.65kw │   1_009.03w │   1_009.03w │      1.88% │
│ twitter-big │ 18_546.65us │ 3_697.06kw │ 190_906.45w │ 190_906.45w │    100.00% │ …
```
=> bigstring-intrinsics: use them

benchmarks/pure_benchmark.ml, lib/angstrom.ml
The helper parsers used to construct character parsers were too heavyweight, and required additional allocation. Special-case some of them to avoid that.
=> char-parsers: optimize character parsers for allocation

benchmarks/pure_benchmark.ml, examples/rFC7159.ml, lib/angstrom.ml
```
┌────────────────┬──────────┬─────────┬────────────┐
│ Name           │ Time/Run │ mWd/Run │ Percentage │
├────────────────┼──────────┼─────────┼────────────┤
│ peek_char_fail │  11.09ns │   9.00w │     62.85% │
│ any_char       │  12.62ns │   9.00w │     71.49% │
│ char           │  15.75ns │  15.00w │     89.22% │
│ not_char       │  17.65ns │  15.00w │    100.00% │
│ advance 1      │   8.24ns │   9.00w │     46.69% │
└────────────────┴──────────┴─────────┴────────────┘
```
=>  json-advance: the best way to skip over a char is advance 1

lib/angstrom.ml, lib/input.ml, lib/input.mli, lib/more.ml, lib/more.mli, lib/parser.ml
The main `angstrom.ml` file was difficult to read due to the fact that it had many different submodules. Move some of those submodules into their own files. Hopefull this will improve readability and maintainability.
=> Move submodules into separate files

benchmarks/pure_benchmark.ml, lib/angstrom.ml, lib_test/test_angstrom.ml
The `count_while f >>= advance` pattern was a signifcant source of parser allocations. Elminiate that pattern by passing a `with_buffer` function to count_while, which will be passed a view into the input that count_while will consume. The result of `with_buffer` is now the result of the parser.
This pull request also adds some looping benchmarks that were used to evaluate the change, together with existing json benchmarks.
Before:
```
┌──────────────────┬──────────┬────────────┬──────────┬──────────┬───────────┬──────────┬────────────┐
│ Name             │ Time/Run │    mWd/Run │ mjWd/Run │ Prom/Run │   mGC/Run │ mjGC/Run │ Percentage │
├──────────────────┼──────────┼────────────┼──────────┼──────────┼───────────┼──────────┼────────────┤
│ skip_while  true │   1.92us │     23.00w │ …
```
=> optimize uses of count_while

lib/angstrom.ml
`caml_equal`'s an indirect call, it should be avoided.
=> eliminate-caml_equal: slipped through

lib/angstrom.ml, lib/angstrom.mli
This parser can be used for efficient look-ahead, which also doesn't allocate in the fast path.
=> peek: Add Unsafe.peek parser

benchmarks/pure_benchmark.ml
There was a problem with the http benchmark where it would only parse the first request in the input file. Adding a `skip_many` around the request parser fixes that.
=> fix-http-bench: add skip_many to parse the entire file

benchmarks/pure_benchmark.ml
Avoids a deprecation warning and also plays nicely with `-safe-string`.
=> bench-safe-string: use bytes instead of string as read buffer

async/angstrom_async.ml, lib/angstrom.ml, lib/angstrom.mli, lib/input.ml, lib/input.mli, lib/parser.ml
The names of functions from the input module were pretty bad. This commit fixes that and in the process expands functionality of the unbuffered interface. Rather than requiring a bigstring as an input, the client can specify a range of bytes to use as input within the bigstring, specified by the `off` and `len` arguments of the `continue` field of the `partial` types. These changes had to be propagated through the unbuffered interface as well.
To simplify implementation at a negligible cost to user convenience, the `parse` functions in both the `Unbuffered` and `Buffered` modules no long take an initial input as an argument. For one-shot parses, there are already convenience functions for that. In other words if you're using these modules then you probably already have an input driver …
=> Input module reorg

lib/parser.ml
For some reason `Monad.return` was being defined as an anonymous function being assigned to an identifier. Just turn it into a regular function definition.
Not sure why it was like that to begin with.
=> return: use function definition syntax

lib/angstrom.ml, lib_test/test_angstrom.ml
On a failed prompt call, the position was not being reset to the position at the start of the `count_while` or `count_while1`, rather than taking into account the consumed input. In practice this would be difficult to detect as the end of input was reached, except when checking if the next parser was checking if it was the end of the input!
This commit fixes the bug and adds regression tests.
=> count_while-bug: fix bug in count_while and count_while1

lib/angstrom.ml
This reverses the fix introduced by #104, which actually hid a bug in the old `Input.uncommitted_bytes`. That function  using the buffer length rather than the input length to compute the number of uncommitted bytes. As part of the refactoring performed in #123, this bug was fixed. So despite the removal of the fix in #104, the test introduced in the same pull request continues to pass.
=> bad-check: remove redundant check that hid a bug

benchmarks/pure_benchmark.ml, lib/angstrom.ml, lib/angstrom.mli, lib/input.ml, lib/input.mli, lib_test/test_angstrom.ml
Add int parsers that take various int types as an argument and ensure that the corresponding number of bytes match the beginning of the input.
These parsers are useful for checking protocol constants, and should be more efficient than the newly-named `any_intN` parsers. These previous parsers required a bind in order to perform this check, whereas the new parsers do not.
In addition to adding these new parsers, which were more efficient than the previous alternatives, an internal refactoring improved the performance and allocation requirements of the `any_intN` parsers and the `string` parser. Here's a benchmark for parsers that check for a `"\r\n"` sequence before (including the initial implementation of the new parsers):
```
┌────────────────────┬──────────┬─────────┬────────────┐
│ …
```
=> Add constant-checking int parsers

lib/angstrom.ml, lib/angstrom.mli
This can be used to quickly identify which choice resulted in the failure of the parser. In the absence of `commit`, it's always the first choice encountered, but it gets trickier when a parser does use choice. In that case it's the first choice encountered after the last `commit`.
Closes #136.
=> choice-error: add an optional `failure_msg` argument to `choice`

lib/angstrom.mli
Documentation is not clear about `take_bigstring*`. I'm not sure if it's the better way to explicit than we copy resulted `bigstring` (than to use `sub`) but it seems important to explicit this behavior.
=> Better documentation about take_bigstring*

lib/parser.ml, lib_test/test_angstrom.ml
The failure contination in choice was previously checking `client_committed_bytes` to determine if it was OK to backtrack to the previous position to try the next branch of the choice. The code should have been checking `parser_committed_bytes` instead, which is the value that's actually updated by the `commit` parser.
Added a test to catch this in the future.
Closes #144.
=> fix-choice-commit: check parser_committed_bytes

angstrom-async.descr, angstrom-async.opam, angstrom-lwt-unix.descr, angstrom-lwt-unix.opam, angstrom-unix.descr, angstrom-unix.opam, angstrom.descr, angstrom.opam, lwt/angstrom_lwt_unix.ml, lwt/angstrom_lwt_unix.mli
Allow the resumption of a parse that results in unconsumed data via the
creation of a Buffered parser state.
Closes #154
=> lwt: implement parse_with_buffered_state

lib/angstrom.mli
The docstring claimed to return `Some (bs, v)` when in reality it returns `Some v`.
Refs:
https://github.com/inhabitedtype/angstrom/blob/3a3e245b6f1b300faaf964629e089dca311dbf68/lib/angstrom.ml#L118-L120
=> Fix the `Angstrom.Buffered.state_to_option` docstring

lib/angstrom.ml, lib_test/test_angstrom.ml
The `advance` docstring states that `advance` will fail if the remaining
input is less than `n`. However, it seems like this is not actually the
case in practice.
This PR proposes that `advance` abides by what's stated in the
docstring. In practice I was seeing Angstrom report that it consumed
more input than the available input length, which is what led to
`Bigstringaf.blit` getting a negative length (related PR:
https://github.com/inhabitedtype/bigstringaf/pull/25) happening in the
first place.
=> Fix `Angstrom.advance` to fail if the remaining input is less than n

lib/angstrom.mli
This has no functional change to the interface but makes clearer when certain type parameters are being ignored.
I wasn't sure about the `'b` -> `'a` changes, so feel free to change these `'a`s back to `'b`s if that looks clearer.
=> Use underscores for unused type parameters

lib/angstrom.ml, lib/angstrom.mli, lib_test/test_angstrom.ml
Equivalent to the `char` constructor but takes an int as an argument and uses its lower-order byte to match against the current byte in the input.
=> int8: add int8 constructor

lib/input.mli
I can't remember how this thing works without the diagram. Maybe someone else will find it useful.
=> add a helpful comment to input.mli

lib/angstrom.ml, lib/input.ml, lib/input.mli
They don't to bounds checks so call them unsafe.
Closes #174
=> mark-unsafe: rename unsafe input operations

lib/angstrom.ml
=> un-reensure: eliminate redundant length checks in int parsers

lib/input.ml, lib_test/test_angstrom.ml
Fix the bug reported in #180 and test it.
When an input is provided with a corresponding `off` and `len`, that means that `[off, off + len)` is the valid range of the input. The upper bound that the code was previously using was `len`, which was incorrect.
=> Input bugfix

lib/input.ml, lib_test/test_angstrom.ml
This fixes the bug introduced by #181, which was a bugfix for a bug reported in #180.
Before #181, when a non-zero `off` into the current input buffer was provided, the loop was conservative in what it would consume: rather than attempting to consume characters in the range `[off, off + len)`, it would only consider the characters in the range `[0, len)`.
#181 changed this so that it considered the range `[off, idx + len)` where `idx` is the current position in the input buffer. This seemingly worked on simple parsers. However for more complex parsers this led to unsafe memory accesses when determining how much of the input to consume, and that resulted in a length that ran over the end of the input buffer. When an `take_while*` parser then tried to return the bytes to the user, a checked …
=> input-bugfix-take-2: proper bugfix

async/angstrom_async.ml, lib/angstrom.ml, lib/angstrom.mli, lib/exported_state.ml, lib/parser.ml, lib_test/dune, lib_test/test_angstrom.ml, lib_test/test_json.ml
This is an alternative implementation to #186 that doesn't change the interface at the cost of translating between the internal and external state. I am not sure how to measure the impact of the additional allocation.
It seems to me that it would only matter for cases with lots of `Partial` state (e.g. feeding one char at a time).
=> Make [Angstrom.fix] friendly with js_of_ocaml (Alternative to #186)

async/angstrom_async.ml, lib/angstrom.ml, lib/angstrom.mli, lib/parser.ml, lib_test/dune, lib_test/test_angstrom.ml, lib_test/test_json.ml
It solves https://github.com/inhabitedtype/angstrom/issues/95
This is heavily inspired by @dinosaure and @SGrondin but tries to keep the performance of native code untouched.
cc @tyoverby
Json benchmark before
```
Estimated testing time 40s (4 benchmarks x 10s). Change using '-quota'.
┌─────────────┬─────────────┬────────────┬─────────────┬─────────────┬────────────┐
│ Name        │    Time/Run │    mWd/Run │    mjWd/Run │    Prom/Run │ Percentage │
├─────────────┼─────────────┼────────────┼─────────────┼─────────────┼────────────┤
│ twitter1    │     15.15us │     4.55kw │       6.16w │       6.16w │      0.14% │
│ twitter10   │    106.55us │    28.01kw │     161.12w │     161.12w │      0.95% │
│ twitter20   │    214.54us │    54.58kw │     594.46w │     594.46w │      1.92% │
│ …
```
=> Make [Angstrom.fix] friendly with js_of_ocaml

lib/angstrom.ml, lib/angstrom.mli, lib_test/test_angstrom.ml
Foreword: I can't tell if this is a weird thing to propose. I don't think I've seen something similar in another parser combinator library, but I don't know how to do the thing I want to do elegantly without it. I think one of the tests best demonstrates what I'm trying to do:
```ocaml
let integer =
option '+' (char '-') *> take_while (function '0'..'9' -> true | _ -> false)
in
check_int ~msg:"parsing an integer" (consumed integer >>| int_of_string)
["-12345"] (-12345)
```
It might seem a little contrived, as I'm using another parser (`int_of_string`) after the `consumed`, but in the case of `jsonaf`, the user provides a similar `string -> 'a` parser outside of the angstrom parsing. Trying to write this without `consumed` means parsing chars and strings and awkwardly concatenating them. …
=> add `consumed` combinator

lib/angstrom.mli
Any parser exposed in this section will be part of the public API but will not be documented. People that want to use them should read the code to fully understand what they're doing.
Caveat emptor for the whole library, but even moreso for this.
Closes #184.
=> expert: expose pos and available in the public API

.travis.yml, angstrom.opam, dune-project, lib/angstrom.ml, lib/angstrom.mli, lib/dune, lib_test/dune, lib_test/test_let_syntax_native.ml, lib_test/test_let_syntax_ppx.ml
Notes:
I upgraded the minimum dune version from 1.0 to 1.8 in order to use the future_syntax preprocessor, which grant the native let-syntax backwards-compatibility to earlier compiler versions.  If you don't want that high of a dune requirement, we'll have to bail on native let-syntax.
The ppx_let version requirement is because that seems to be the first version that supports `let%mapn`.
For testing I just wanted to ensure a few things compile.  The way I did this was to have one of the test executables depend on the compilation of these two files I care about, even though it doesn't use them at all.  I couldn't come up with a better way to include building the library in the runtest alias, but I don't feel great about it.
=> add both native and ppx let-syntax support, and corresponding tests

angstrom.opam
Angstrom used to need the result compatibility package (for OCaml < 4.03).
Since Angstrom requires OCaml 4.04, there is no need for this extra dependency.
=> opam: remove unneeded result dependency

benchmarks/pure_benchmark.ml
Error was:
File "benchmarks/pure_benchmark.ml", line 25, characters 6-10:
25 |     | Ok _ -> ()
^^^^
Error: This pattern matches values of type ('a, 'b) result
but a pattern was expected which matches values of type
consume:Angstrom.Consume.t -> ('c, string) result
=> Fix compilation error

lib/angstrom.mli
See https://github.com/ocaml/ocaml/pull/2041 for the fix in OCaml 4.08.0
Detected while running the tests for emile 0.2 to 0.5 on OCaml 4.07 in https://github.com/ocaml/opam-repository/pull/18758 (cc @dinosaure):
```
#=== ERROR while compiling emile.0.5 ==========================================#
```
=> Remove an unwanted dependency toward the bigarray library in OCaml 4.07
